### ISSUE TITLE
Azure AD group sync broken after v0.0.17 upgrade

### ISSUE THREAD

**Issue by muyari** [redhat-cop/group-sync-operator#184]
OpenShift Version 4.9.25

The group sync operator updated this morning to v0.0.17 and now Azure group sync has stopped working. I have deleted the the operator, the groupsync and even the project and redeployed.

The only issue I can see is that two conditions are stuck in pending:

PendingTrue
Apr 12, 2022, 11:39 AM
RequirementsUnknownrequirements not yet checked

PendingTrue
Apr 12, 2022, 11:39 AM
RequirementsNotMetone or more requirements couldn't be found

Anyone else experiencing this issue?

**Comment by sabre1041** [comment]
Can you provide additional details? I had deployed on an OCP 4.9 cluster today as well sucessfully

**Comment by muyari** [comment]
I'm not sure what additional info to provide :(. The two pending msgs on the operator is the only thing I can see that might be an issue.

I have 6 azure ad groups replicated into OpenShift via the operator and none are being updated. The configured "GroupSync" has a status of "Condition: ReconcileSuccess" so it seems to be working but the group membership does not update under openshift groups.

**Comment by sabre1041** [comment]
Can you confirm the v0.0.17 operator is currently running?

Are there any errors in the operator? Can you also provide the full `GroupSync` CR?

**Comment by muyari** [comment]
The operator is running, its status is "Succeeded". No errors under events, and the only issue I can see on the operator is those two pending msgs.

Here is my yaml of the GroupSync

apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  creationTimestamp: '2022-04-12T15:44:23Z'
  generation: 1
  managedFields:
    - apiVersion: redhatcop.redhat.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:providers': {}
          'f:schedule': {}
      manager: Mozilla
      operation: Update
      time: '2022-04-12T15:44:23Z'
    - apiVersion: redhatcop.redhat.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions':
            .: {}
            'k:{"type":"ReconcileSuccess"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:observedGeneration': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:lastSyncSuccessTime': {}
      manager: manager
      operation: Update
      subresource: status
      time: '2022-04-12T15:44:24Z'
  name: azure-groupsync
  namespace: group-sync-operator
  resourceVersion: '16483809'
  uid: 6488ea5e-6773-4c66-bb60-ef74154dbe5b
spec:
  providers:
    - azure:
        credentialsSecret:
          kind: Secret
          name: azure-group-sync
          namespace: group-sync-operator
        groups:
          - <our list of groups>
      name: azure
  schedule: '*/5 * * * *'
status:
  conditions:
    - lastTransitionTime: '2022-04-12T19:19:00Z'
      message: ''
      observedGeneration: 1
      reason: LastReconcileCycleSucceded
      status: 'True'
      type: ReconcileSuccess
  lastSyncSuccessTime: '2022-04-12T19:19:00Z'

**Comment by sabre1041** [comment]
Can you elaborate on why there is an empty `groups` parameter? this field is intended to limit the groups that are synchronized into OpenShift

**Comment by muyari** [comment]
I just removed them for the post as it would be the only item that is organizational specific and did not want to post the name of our groups on a public forum.

**Comment by muyari** [comment]
spec:
  providers:
    - azure:
        credentialsSecret:
          kind: Secret
          name: azure-group-sync
          namespace: group-sync-operator
        groups:
          - group01
          - group02
          - group03

**Comment by sabre1041** [comment]
I just tested out the operator in my environment and my tests passed (when providing a similar configuration as you presented).

Can you check the logs of the operator itself to see if any errors are being emitted?

**Comment by muyari** [comment]
I0412 15:39:23.216378       1 main.go:180] Valid token audiences:
I0412 15:39:23.216535       1 main.go:316] Reading certificate files
I0412 15:39:23.216618       1 reloader.go:98] reloading key /etc/certs/tls/tls.key certificate /etc/certs/tls/tls.crt
I0412 15:39:23.216861       1 main.go:350] Starting TCP socket on 0.0.0.0:8443
I0412 15:39:23.220027       1 main.go:357] Listening securely on 0.0.0.0:8443

This is what i got and it would appear to be ok from what i see in these logs.

**Comment by muyari** [comment]
Here is some additional info as well: (also looks good)

group-sync-operator-controller-manager-cd87b9766-4rbc6
Running

Conditions
TypeStatusUpdatedReasonMessage
InitializedTrue
Apr 12, 2022, 11:39 AM
--
ReadyTrue
Apr 12, 2022, 11:39 AM
--
ContainersReadyTrue
Apr 12, 2022, 11:39 AM
--
PodScheduledTrue
Apr 12, 2022, 11:39 AM
--

**Comment by DomDaigle** [comment]
Hi everyone, 

I add the same issue. So, i rolled back to 0.0.16 and it work great. I don't know how I can help on that case. But , ask me what you need..  


By the way i'm a bit newbie in openshift.. But, still can help 

Thank you

**Comment by muyari** [comment]
Awesome @DomDaigle, I was wondering if roll back was a possibility!! I will attempt that once I figure out how to do it!

**Comment by sabre1041** [comment]
@DomDaigle @muyari I just ran through everything.

Can you confirm your application registration has the following permissions
<img width="1029" alt="Screen Shot 2022-04-12 at 6 13 19 PM" src="https://user-images.githubusercontent.com/1191285/163070686-fb96a778-5401-4f7d-8762-5b6278e29d64.png">

**Comment by muyari** [comment]
Yes it has the permissions you listed.

**Comment by sabre1041** [comment]
@muyari can you share the logs from the `manager` container?

**Comment by DomDaigle** [comment]
@sabre1041 yes it has at least all permission as you show ! 
![image](https://user-images.githubusercontent.com/22457577/163077161-b7173f60-ccad-488f-a614-3110b07d8fd0.png)

you could look to the controler log I sent in my first comment..  But everything looks good !!

**Comment by sabre1041** [comment]
@DomDaigle everything looks aok from your side. If you remove the restrictions on groups, do any groups populate?

**Comment by DomDaigle** [comment]
@sabre1041 not sure what restriction your are asking to remove.

**Comment by sabre1041** [comment]
@DomDaigle You have the following defined

```
  groups:
    - secaro-dev-admin
    - secaro-dev-access
    - secaro-dev-reader
```

This limits the groups that are ultimately synchronized. Would you be able to remove this section to test whether any groups are synchronized?

Thanks for working through this together. We will be sure to get this identified and resolved in short order

**Comment by DomDaigle** [comment]
@sabre1041  I removed the group in openshift directly and it didn't recreate it.  

So, today i will remove the groups in the groupsync ressource and let you know !

Thank you

**Comment by DomDaigle** [comment]
@sabre1041 Here's what I did : 
- upgrade from 0.0.16 to 0.0.17
- check yaml groupsSync Config and saw status reconciled error
- remove groupsSync config
- create new groupsSync Config from UI and no group in it . 
  - Had to remove all others providers in the yaml because it don't let me add new config.

  result: Import all AAD Groups (+1000).. ;( 

- remove all groups synced from AAD
- Specify the groups to sync directly in the YAML:
 `groups:
        - secaro-dev-reader
 `

result: 
  Did not sync that group secaro-dev-reader

I'm sending some log and yaml config whit there status. 

[groupsync-azure-groupsync.yaml.txt](https://github.com/redhat-cop/group-sync-operator/files/8491644/groupsync-azure-groupsync.yaml.txt)
[clusterserviceversion-group-sync-operator.v0.0.17.yaml.txt](https://github.com/redhat-cop/group-sync-operator/files/8491645/clusterserviceversion-group-sync-operator.v0.0.17.yaml.txt)
[group-sync-operator-controller-manager-77966cc484-sq6rk-manager.log](https://github.com/redhat-cop/group-sync-operator/files/8491646/group-sync-operator-controller-manager-77966cc484-sq6rk-manager.log)

**Comment by sabre1041** [comment]
@DomDaigle It appears the operator is functioning correctly, but is not matching the name of the group (The operator performs simple filtering of results based on the "Display Name".

Can you confirm the Display Name of the group matches the property specified?

**Comment by muyari** [comment]
@DomDaigle 

I'm still having issues reverting to .16, should I be able to apply the yaml you posted earlier to install the operator? (yaml below)

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
labels:
operators.coreos.com/group-sync-operator.group-sync-operator: ''
name: group-sync-operator
namespace: group-sync-operator
spec:
channel: alpha
installPlanApproval: Manual
name: group-sync-operator
source: community-operators
sourceNamespace: openshift-marketplace
startingCSV: group-sync-operator.v0.0.16

I'm getting some errors when trying to apply "resource name may not be empty"

**Comment by sabre1041** [comment]
@muyari @DomDaigle Trying to understand where we are both at with this issue. It seems like it is an issue only when attempting to perform filtering based upon group name. As @DomDaigle shared, it looks like syncing works without restricting based on group. Can you confirm this is the case? Unfortunately, I am not facing a similar issue in my environment and it is a bit difficult to replicate. 

I'd be happy to look into spinning up a "one off" operator that can provide much more debug logging if you are interested.

**Comment by muyari** [comment]
I am in the same situation as @DomDaigle I need group filtering as we have 10000+ groups (due to ms teams). We would like to filter in only the groups that we will leverage in OpenShift.

I would be open to deploying the "one off" operator however any logging that is produced I will need to review for any sensitive info prior to posting. (if any).

**Comment by sabre1041** [comment]
@muyari Here is a command that you can use to deploy a custom image. It contains debug logging that we can use to investigate

```
kubectl patch csv -n group-sync-operator group-sync-operator.v0.0.17 -type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/ablock/group-sync-operator:issue-185"}]'
```

Looking at your issue in more detail, depending on the structure of your AAD tree, you can leverage additional filtering logic (such as if all groups are nested within a single group or to use the `filter` fetaure)

**Comment by muyari** [comment]
what the equivalent oc command to replace kubectl?

**Comment by sabre1041** [comment]
just replace `kubectl` with `oc`

**Comment by muyari** [comment]
Getting the  following error:

oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 -type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/ablock/group-sync-operator:issue-185"}]'

Error: unknown shorthand flag: 't' in -type=json

See 'oc patch --help' for usage.

oc patch --help
Update field(s) of a resource using strategic merge patch, a JSON merge patch, or a JSON patch.

 JSON and YAML formats are accepted.

Usage:
  oc patch (-f FILENAME | TYPE NAME) [-p PATCH|--patch-file FILE] [flags]

Examples:
  # Partially update a node using a strategic merge patch. Specify the patch as JSON.
  oc patch node k8s-node-1 -p '{"spec":{"unschedulable":true}}'
  
  # Partially update a node using a strategic merge patch. Specify the patch as YAML.
  oc patch node k8s-node-1 -p $'spec:\n unschedulable: true'
  
  # Partially update a node identified by the type and name specified in "node.json" using strategic merge patch.
  oc patch -f node.json -p '{"spec":{"unschedulable":true}}'
  
  # Update a container's image; spec.containers[*].name is required because it's a merge key.
  oc patch pod valid-pod -p '{"spec":{"containers":[{"name":"kubernetes-serve-hostname","image":"new image"}]}}'
  
  # Update a container's image using a json patch with positional arrays.
  oc patch pod valid-pod --type='json' -p='[{"op": "replace", "path": "/spec/containers/0/image", "value":"new image"}]'

Options:
      --allow-missing-template-keys=true: If true, ignore any errors in templates when a field or map key is missing in
the template. Only applies to golang and jsonpath output formats.
      --dry-run='none': Must be "none", "server", or "client". If client strategy, only print the object that would be
sent, without sending it. If server strategy, submit server-side request without persisting the resource.
      --field-manager='kubectl-patch': Name of the manager used to track field ownership.
  -f, --filename=[]: Filename, directory, or URL to files identifying the resource to update
  -k, --kustomize='': Process the kustomization directory. This flag can't be used together with -f or -R.
      --local=false: If true, patch will operate on the content of the file, not the server-side resource.
  -o, --output='': Output format. One of:
json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-as-json|jsonpath-file.
  -p, --patch='': The patch to be applied to the resource JSON file.
      --patch-file='': A file containing a patch to be applied to the resource.
      --record=false: Record current kubectl command in the resource annotation. If set to false, do not record the
command. If set to true, record the command. If not set, default to updating the existing annotation value only if one
already exists.
  -R, --recursive=false: Process the directory used in -f, --filename recursively. Useful when you want to manage
related manifests organized within the same directory.
      --show-managed-fields=false: If true, keep the managedFields when printing objects in JSON or YAML format.
      --template='': Template string or path to template file to use when -o=go-template, -o=go-template-file. The
template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].
      --type='strategic': The type of patch being provided; one of [json merge strategic]

Use "oc options" for a list of global command-line options (applies to all commands).

**Comment by sabre1041** [comment]
@muyari It should be `--type`

```
oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/ablock/group-sync-operator:issue-185"}]'

```

**Comment by muyari** [comment]
new error:

Error from server (NotFound): clusterserviceversions.operators.coreos.com "group-sync-operator.v0.0.17" not found

**Comment by sabre1041** [comment]
Find the version if the csv installed

oc get csv -n group-sync-operator

**Comment by muyari** [comment]
Do I need to have the group sync operator installed before running the following?:

oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/ablock/group-sync-operator:issue-185"}]'

**Comment by sabre1041** [comment]
yes

**Comment by muyari** [comment]
ok my bad, I will install and try again! 5min.

**Comment by muyari** [comment]
ok it worked now when I did things properly :P. What am I looking for now that I have patched?

**Comment by muyari** [comment]
![image](https://user-images.githubusercontent.com/68556303/163718159-1df79c91-338b-440e-a257-5a76304c6b67.png)

**Comment by muyari** [comment]
actually getting pull errors.

**Comment by sabre1041** [comment]
ugh. can you replace the tag to `issue-184`. I forgot i retagged it with the appropriate issue number

```
oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/ablock/group-sync-operator:issue-184"}]'
```

**Comment by muyari** [comment]
No problem, will run it now

**Comment by muyari** [comment]
Ok I think were good now, no more pullback errors.

**Comment by muyari** [comment]
2022-04-17T14:24:00.660Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "Our_Group-01", "Group Being Tested Display Name": "SP05 Team 32/33"}
2022-04-17T14:24:00.660Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "Our_Group-01", "Group Being Tested Display Name": "SP05 Team 32/33"}
2022-04-17T14:24:00.660Z	INFO	controllers.GroupSync	Sync Completed Successfully	{"groupsync": "group-sync-operator/azure-groupsync", "Provider": "azure", "Groups Created or Updated": 0, "Groups Pruned": 0}

**Comment by muyari** [comment]
Allowed groups not matched for everything??

**Comment by muyari** [comment]
guess its just not picking up on the groups I want to sync configured in the GroupSync?

**Comment by sabre1041** [comment]
if you look at the logging. you should see the operator iterating through all of the groups that were retrieved and comparing them to the fields that you specified

**Comment by muyari** [comment]
yeah I see that, problem is that every single line has this "DEBUG: Allowed Groups **NOT** Matched!". I have checked my GroupSync and the groups I want to sync are good, no typo's or mistakes.

**Comment by sabre1041** [comment]
Do you see the name of the group that you want matched present?

**Comment by muyari** [comment]
![image](https://user-images.githubusercontent.com/68556303/163719164-fb77fddd-c9fb-4800-970c-0a5121923797.png)

So here is the actual group however Im not sure why after the comma there is "Group Being Tested Display Name": "OTSO-YPN Steering Committee Team"

**Comment by muyari** [comment]
seems like there are a bunch of comma delimited groups on each line. Is this the way you would expect things to be?

**Comment by muyari** [comment]
looks funky to me.

**Comment by muyari** [comment]
I also find it strange that I see the desired groups over and over again:

2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG_AAD", "Group Being Tested Display Name": "IPS National MG Meeting – Réunion MG nationale du SPI"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG", "Group Being Tested Display Name": "IPS National MG Meeting – Réunion MG nationale du SPI"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG_AAD", "Group Being Tested Display Name": "Insolvency Team Leaders"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG", "Group Being Tested Display Name": "Insolvency Team Leaders"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG_AAD", "Group Being Tested Display Name": "Insolvency Team Leaders"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG", "Group Being Tested Display Name": "Insolvency Team Leaders"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG_AAD", "Group Being Tested Display Name": "LDA TRAINING"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG", "Group Being Tested Display Name": "LDA TRAINING"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG_AAD", "Group Being Tested Display Name": "LDA TRAINING"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG", "Group Being Tested Display Name": "LDA TRAINING"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG_AAD", "Group Being Tested Display Name": "Réunion d'équipe Stacy"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG", "Group Being Tested Display Name": "Réunion d'équipe Stacy"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG_AAD", "Group Being Tested Display Name": "Réunion d'équipe Stacy"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG", "Group Being Tested Display Name": "Réunion d'équipe Stacy"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG_AAD", "Group Being Tested Display Name": "Riverdale"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG", "Group Being Tested Display Name": "Riverdale"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG_AAD", "Group Being Tested Display Name": "Riverdale"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG", "Group Being Tested Display Name": "Riverdale"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG_AAD", "Group Being Tested Display Name": "Discussion"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG", "Group Being Tested Display Name": "Discussion"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG_AAD", "Group Being Tested Display Name": "Discussion"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG", "Group Being Tested Display Name": "Discussion"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG_AAD", "Group Being Tested Display Name": "SP05 Team 32/33"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-AllAccess_A_DG", "Group Being Tested Display Name": "SP05 Team 32/33"}
2022-04-17T14:38:01.383Z	INFO	syncer_azure	DEBUG: Allowed Groups **NOT** Matched!	{"Allowed Group Name": "CloudNuage_CloudOps-Admins-Regular_A_DG_AAD", "Group Being Tested Display Name": "SP05 Team 32/33"}

**Comment by sabre1041** [comment]
This is just logr formatting. There are two messages that are being printed. the first is one of the "allowed" groups that you have declared in the `GroupSync` CR. The second (Group being tested) is one of the values that was returned from AAD.

I assume `CloudNuage_CloudOps-Admins-AllAccess_A_DG_AAD` is one of the groups that you have specified in the GroupSync CR? Do you see if being printed in the "Group Being Tested Display Name"?

**Comment by muyari** [comment]
And that's not even all the entries, I would say close to 100 lines.

**Comment by muyari** [comment]
Yes "CloudNuage_CloudOps-Admins-AllAccess_A_DG_AAD" is a desired group and is in the group Sync.

Im not sure what you mean by "Do you see if being printed in the "Group Being Tested Display Name"?"

**Comment by sabre1041** [comment]
That is exactly what i was thinking as well. its a large dataset and it not iterating through all of them. my testing was using a somewhat small group list (7) groups. I could perform some testing to see if its indeed not iterating through them all

**Comment by muyari** [comment]
there are definitely a lot of group due to teams in our org. we have 50k + employees and teams groups create a Azure Ad group for membership.

We have over 22000 azure ad groups in our tenant.

**Comment by muyari** [comment]
not sure if that poses an issue but I thought I will give you more info if it helps.

**Comment by muyari** [comment]
My GroupSync is configure to sync 4 aad groups.

**Comment by sabre1041** [comment]
yes. I would HIGHLY recommend using a different approach for querying groups. The method that you are using now will attempt to retrieve all groups and then filter out the results. Take a look at either the `baseGroups` or `filter` options. 

Can you estimate how many total group are being returned in the logs? 10? 100?

**Comment by muyari** [comment]
it seems to cap at 1000 lines

**Comment by muyari** [comment]
lots of duplication in the group names from what i can see for some reason.

**Comment by muyari** [comment]
Is there any documentation "Take a look at either the baseGroups or filter options." <-- for this? Also i would like to point out that before the upgrade we had been using it as is for a few month with no issues it worked amzing!

**Comment by sabre1041** [comment]
Correct. It is being extremely verbose. If will take each returned group from AAD and print out whether it matches the groups that you have specified in the `groups` field. How many unique groups are returned? 

This is most likely due to the new official library from Microsoft that we are now using. If you can provide the number of unique groups that are being returned, I'll be able to test and confirm that iterating through all possible groups works as intended

**Comment by muyari** [comment]
well each time it runs it seems to cap at 1000 lines. I do see a lot of duplication in the logs so I would hazard a guess of around 800 unique groups during each run that are trying to match.

Seeing that we have 22k + groups why would I not see more entries when it iterates through each group name for a match?

I'm open to trying the baseGroups or filter option if you could guide me as to how to configure the required options.

**Comment by sabre1041** [comment]
Its most likely a pagination issue where the operator needs to request the next set of results. 

I'll work on testing out what it will take in the next day or so and then provide updates as appropriate

**Comment by muyari** [comment]
Awesome! thanks so much @sabre1041 you have been very helpful :). By any chance is there an easy way I can get back to v.16? until you have figured out the changes?

I tried downloading the previous repo and running the manual install commands but it never ends up working.

**Comment by muyari** [comment]
It would be awesome if when installing via operator hub we could select the current version and the previous version so that we can revert if needed.

**Comment by sabre1041** [comment]
The is not an elegant way to revert to an older version since it appears that only one version is available in OperatorHub. 

You should be able to set the image back to the older version since there were no drastic API changes. Just patch the CSV to version v0.0.16

```
oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/redhat-cop/group-sync-operator:v0.0.16"}]'
```

**Comment by muyari** [comment]
Awesome! I will patch with this and see how it goes. Do I need to re-install everything or running the line above will kill off the old pod and get the .16 pod?

**Comment by muyari** [comment]
Amazing setting the image back to v0.0.16 has us back up and running :). Thanks so much for you assistance on this issue @sabre1041!! I look forward to the updates of this awesome operator!!

**Comment by sabre1041** [comment]
@muyari I have hopefully addressed the paging issue in this "preview" image. It does not contain any of the additional logging as the custom image that we tested earlier, but let me know if your groups are now synchronized.

You should be able to patch the CSV with the image `quay.io/ablock/group-sync-operator:azure-paging`

```
oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/ablock/group-sync-operator:azure-paging"}]'
```

**Comment by DomDaigle** [comment]
@sabre1041 and @muyari I was out for couples of days (easter hollyday).    So, I read your posts and what I can tell is that we have thousands of groups and it's look like groups sync take only 100 to compare. So, i used the "baseGroups" param and add the prefix name of those groups.   Strange things happened.  The log show an error, but the groups were sync..  And the status said 0 created or update !!  strange !

`2022-04-19T18:07:54.602Z	INFO	controllers.GroupSync	Beginning Sync	{"groupsync": "group-sync-operator/azure-groupsync", "Provider": "azure"}
2022-04-19T18:07:55.699Z	INFO	syncer_azure	Failed to find a single base group to search from	{"Provider": "azure", "Base Group": "secaro"}
2022-04-19T18:07:55.699Z	INFO	controllers.GroupSync	Sync Completed Successfully	{"groupsync": "group-sync-operator/azure-groupsync", "Provider": "azure", "Groups Created or Updated": 0, "Groups Pruned": 0}`

**Comment by DomDaigle** [comment]
> @DomDaigle
> 
> I'm still having issues reverting to .16, should I be able to apply the yaml you posted earlier to install the operator? (yaml below)
> 
> apiVersion: operators.coreos.com/v1alpha1 kind: Subscription metadata: labels: operators.coreos.com/group-sync-operator.group-sync-operator: '' name: group-sync-operator namespace: group-sync-operator spec: channel: alpha installPlanApproval: Manual name: group-sync-operator source: community-operators sourceNamespace: openshift-marketplace startingCSV: group-sync-operator.v0.0.16
> 
> I'm getting some errors when trying to apply "resource name may not be empty"

I was out out for couples of days..  But I think @sabre1041  give you the answer further in the discussion.  am I right ?

**Comment by sabre1041** [comment]
@DomDaigle a few things.

1. if you have prior group(s) that were synchronized prior to the using the operator. If so, you would need to delete the groups and then have the operator synchronize all of the groups
2. `baseGroups` was added to support nested groups so that you can start from a particular group instead of synchronizing all groups. The full name of the group is required

**Comment by sabre1041** [comment]
@muyari Have you had the chance to review the "preview" image?

**Comment by DomDaigle** [comment]
@sabre1041  Ok !  So if I recap this issue. The difference between 0.0.16 and 0.0.17, from my POV, considering that we have more over 100 groups,  is that I need to add the options "filter"  or "baseGroups" in the config.  Those options works for me ! 
I don't know if you can add it to the change log. But, maybe you could add this info to the documentation.  

For me, this issue is resolved.

It was a pleasure to work on that issue with you. So, if you need more info/help. Just ask me ... 

Thank you 
Dominic

**Comment by jaahin14** [comment]
@sabre1041 
Want to tell you that even we also faced the same issue what muyari have faced that group sync is not happening on version v0.0.17.

And the command which you have given to patch the older version of operator v0.0.16 --> After doing it its working perfectly and able to sync new Group.

oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/redhat-cop/group-sync-operator:v0.0.16"}]'

This command helped to work fine on Group Sync things. Can you check once what make any such difference in v.0.0.17 version.

Thanks for your wonderful suggestion

**Comment by jaahin14** [comment]
@sabre1041
Want to tell you that even we also faced the same issue what muyari have faced that group sync is not happening on version v0.0.17.

And the command which you have given to patch the older version of operator v0.0.16 --> After doing it its working perfectly and able to sync new Group with below command which you have given.
oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/redhat-cop/group-sync-operator:v0.0.16"}]'
Can you also help how we can Prune the group which we dont want to add into our environment.?
Like after deleting the name from Group --> Field its not deleting the group and not pruning is happening on v.0.0.16

This command helped to work fine on Group Sync things. Can you check once what make any such difference in v.0.0.17 version.

Thanks for your wonderful suggestion

**Comment by sabre1041** [comment]
@jaahin14 @DomDaigle @muyari I built a test image which should have the updated logic to manage paging large groups. Can you please test in your environments:

```
quay.io/ablock/group-sync-operator:azure-paging
```

**Comment by jaahin14** [comment]
@sabre1041 
Sure I will try to check your above command given and update you in 1 hour

So below command that i have to use right..

oc patch csv -n group-sync-operator group-sync-operator.v0.0.17 --type='json' -p='[{"op": "replace", "path": "/spec/install/spec/deployments/0/spec/template/spec/containers/1/image", "value":"quay.io/ablock/group-sync-operator:azure-paging"}]'

**Comment by sabre1041** [comment]
@jaahin14 yup! I am very interested in resolving this issue so thanks for offering to help test

**Comment by jaahin14** [comment]
Hi @sabre1041 

I just tried to patch "quay.io/ablock/group-sync-operator:azure-paging" but What i am able to se that Prune is not happening.

Example -->
Step -1  Initially I added 2 group --> So both group Synced very well
Step -2 Then I remove 1 group from "kind: GroupSync" yaml file.. But still I am able to see that deleted group inside oc get group  list..

But When we are adding and removing any user from Azure then its perfectly working.

**Comment by sabre1041** [comment]
@jaahin14 lets hold off on pruning as that's separate. Can you confirm at least all groups are synchronizing successfully now with this image?

**Comment by jaahin14** [comment]
Hi @sabre1041 
Yes I am able to sync all group "quay.io/ablock/group-sync-operator:azure-paging" with mentioned image.

**Comment by sabre1041** [comment]
@jaahin14 great to hear! Opened up #188 to resolve this issue. Will continue to track the pruning issue in #169

**Comment by muyari** [comment]
@sabre1041 Sorry I went mia on this issue, but I have also confirmed that the "quay.io/ablock/group-sync-operator:azure-paging" image is working :). Thanks so much for your work on this!!

**Comment by sabre1041** [comment]
@muyari fantastic. we are working through a few CI/Release issues. will be looking to push out `v0.0.18` ASAP
